---
- hosts: efi_recruitment
  become: yes
  become_method: sudo

  vars_prompt:
    - name: project_source
      prompt: Specify path to local project directory
      default: /home/stanley/projects/efi-recruitment/

  tasks:
    - name: Install Nginx
      apt:
        update_cache: true
        name: nginx
        state: latest

    - name: Create directory for SSL certificates
      file:
        path: /etc/nginx/ssl
        state: directory
        mode: '0755'

    - name: Create private key (RSA, 4096 bits)
      community.crypto.openssl_privatekey:
        path: /etc/nginx/ssl/certificate.key

    - name: Create self-signed certificate
      community.crypto.x509_certificate:
        path: /etc/nginx/ssl/certificate.pem
        privatekey_path: /etc/nginx/ssl/certificate.key
        provider: selfsigned

    - name: Configure Nginx
      template:
        src: nginx.j2
        dest: /etc/nginx/sites-available/default

    - name: Restart Nginx
      ansible.builtin.shell:
        cmd: nginx -s reload

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        update_cache: true
        name: docker-ce
        state: latest

    - name: Copy project folder to the EC2 instance
      ansible.builtin.synchronize:
        src: '{{ project_source }}'
        dest: /home/ubuntu/efi-recruitment/
        rsync_opts:
          - '--exclude=node_modules/'

    - name: enable Docker services
      service:
        name: 'docker'
        state: started
        enabled: yes

    - name: Run Docker Compose
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu/efi-recruitment/
